# Generated by Django 5.0.1 on 2024-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profileImage',
            field=models.ImageField(upload_to='users_images/'),
        ),
    ]
